### ISSUE TITLE
instead of removing old images, mark them as deprecated

### ISSUE THREAD

**Issue by spipu** [lxc/lxc-ci#195]
Hi,

i see that when the support on a OS is finished (like for debian jessie), you remove all.

Why you do not just rename then ? like debian-deprecated/jessie for example ?

because in my case, we have (i know it is bad) a server that is always on jessie, and is planned to upgrade soon, and we use LXD for env dev => the fact that the jessie template is not available any more is blocking us if we build the dev env :( 

thanks for all !

**Comment by stgraber** [comment]
You can always build your own images with distrobuilder, so long as the distros still have their package archives online anyway.

We obviously don't like keeping deprecated images around because that may mean people not noticing the image is no longer supported and getting themselves into some very nasty security issues without knowing but also, we have a finite amount of disk space on the various mirrors for this service so keeping old releases would quickly become a problem.
